### ISSUE TITLE
InjectionIII关于不用在每一个controller添加inject方法疑问

### ISSUE THREAD

**Issue by wubiner** [ZHSY/InjectionIIIHelper#1]
你好，请问这篇帖子 https://github.com/su350380433/InjectonIIITools 里的第五点内容，采用runtime时添加class_addmethod方法，我不太理解具体的要修改的ui代码是🏠injectioniiihelper.m文件里的inject方法吗？意思是指所有的controller修改都放在这个方法里添加？？

**Comment by ZHSY** [comment]
对，injected是保存代码、编译完成后，热部署工具调用的方法。
这里用runttime给vc做了统一处理，能覆盖大部分情况下的刷新。
如果不满足需要，你也可以在指定的vc里面实现这个方法，例如：
- (void) injected
{
    //TODO 页面刷新操作
}
