### ISSUE TITLE
大佬有个疑问

### ISSUE THREAD

**Issue by zuqiu123** [ZHSY/InjectionIIIHelper#6]
我不使用你的helper类和使用你的helper类有什么区别吗，没太清除helper带来的好处，求指点

**Comment by ZHSY** [comment]
helper 做了InjectionIII 初始化，并且给view和vc插入了 injected 一个方法，在view和vc中 comm+s 会自动 viewDidLoad ，拖进去就行，不需要做别的。

当然不用helper也行。按照readme中说的，自己初始化InjectionIII，并且在编辑的vc或者view 中 实现 injected 方法就可以了。

helper的代码很简单，你自己看能看懂

**Comment by ZHSY** [comment]
helper 做了InjectionIII 初始化，并且给view和vc插入了 injected 一个方法，在view和vc中 comm+s 会自动 viewDidLoad ，拖进去就行，不需要做别的。

当然不用helper也行。按照readme中说的，自己初始化InjectionIII，并且在编辑的vc或者view 中 实现 injected 方法就可以了。

helper的代码很简单，你自己看能看懂

**Comment by zuqiu123** [comment]
看样子helper是如果只修改了viewdidload的方法，可以不用过去写injected，comm+s 会自动更新， 如果修改了viewdidload以外的代码是不是也要重新写一个injected方法。

2：平时个人的使用，在平时，我不用实现injected也能动态更新，injected似乎是一个通知方法告诉你改好了，我理解是这样的不知道不对不对，求大佬指点

**Comment by ZHSY** [comment]
对，不过helper工具 帮你处理了InjectionIII 路径的初始化，如果不使用的话，你就要自己写初始化，写哪里我都不喜欢，所以就单独拿一个文件放这个了。
